apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  labels:
    app: ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      nodeSelector: 
        kubernetes.azure.com/agentpool: anunode
      containers:
      - name: ingestion-container
        image: anuacr.azurecr.io/axion-ingestion:v2
        env:
          - name: DATABASE_URL
            value: "postgresql://admin:admin123@axion-postgres-service:5432/axiondb"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
