trigger:
  branches:
    include: [main]
  paths:
    include: [axion-telemetry-query-service/*]   

pr: none

stages:
- template: /ADO-pipeline/templates/service-pipeline.yaml
  parameters:
    servicePath: axion-telemetry-query-service
    imageRepo: axion-telemetry-query