trigger:
  branches:
    include: [main]
  paths:
    include: [axion-data-simulator/*]   

pr: none

stages:
- template: /ADO-pipeline/templates/service-pipeline.yaml
  parameters:
    servicePath: axion-data-simulator
    imageRepo: axion-data-simulator 