apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  type: ClusterIP
  selector:
    app: ingestion-service
  ports:
  - port: 8090
    targetPort: 8000